# =========================================================
# Server
# =========================================================
server.port=8081
server.servlet.context-path=/api
spring.config.import=optional:file:.env[.properties]

# =========================================================
# PostgreSQL Cloud
# =========================================================
spring.datasource.url=${POSTGRES_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================================================
# JPA
# =========================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# =========================================================
# MongoDB Cloud
# =========================================================
spring.mongodb.uri=${MONGODB_URI}
# =========================================================
# Redis Cloud
# =========================================================
spring.data.redis.url=${REDIS_URL}
spring.data.redis.ssl.enabled=${REDIS_SSL:true}
# =========================================================
# JWT
# =========================================================
app.jwt.secret=${JWT_SECRET:appchat_jwt_secret_key_2026_minhcong_project_very_long_123456}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

# =========================================================
# Gemini
# =========================================================
app.ai.gemini.api-key=${GEMINI_API_KEY:}
app.ai.gemini.model=${GEMINI_MODEL:gemini-2.5-flash-lite}
app.ai.gemini.url=${GEMINI_URL:https://generativelanguage.googleapis.com/v1beta/models}
